version: '3'
services:
    frontend:
      container_name: frontend
      build:
        context: ./aero-terra-challenge
        dockerfile: Dockerfile
      ports:
        - "8080:5173"
      environment:
        REACT_APP_API_URL: http://backend:3000
      volumes:
        - ./frontend:/app
      command: npm run dev -- --host "0.0.0.0" --port 5173
      depends_on:
        - backend
    
    backend:
      container_name: backend
      build:
        context: ./backend-aero-terra
        dockerfile: Dockerfile
      ports:
        - "3000:3000"
      volumes:
        - ./backend-aero-terra:/app
      command: npm start
